name: Wiederholung Techstarter
run-name: AWS create resources
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      # Wir installieren die dependencies (terraform, aws)
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: Check if aws cli is installed
        run: |
          aws --version
      - uses: hashicorp/setup-terraform@v2
      - run: terraform version
